### ISSUE TITLE
AWS Cloud Pentesting YouTube playlist 

### ISSUE THREAD

**Issue by PunitTailor55** [jassics/awesome-aws-security#15]
Thanks for one stop comprehensive collection of AWS cloud security.

I have created AWS cloud pentesting YouTube playlist

https://youtube.com/playlist?list=PLkfaD6nYyhM229NF7YtRaEOpU8Oc1hchR&si=yg78zMyx_7yXT78U

**Comment by jassics** [comment]
Please raise PR for review.
